name: Deploy to GKE

on:
  push:
    branches:
      - main

env:
  IMAGE: us-central1-docker.pkg.dev/my-gke-project11/nginx-repo/nginx-app

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: my-gke-project11

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE:$GITHUB_SHA .
          docker push $IMAGE:$GITHUB_SHA
          docker tag $IMAGE:$GITHUB_SHA $IMAGE:latest
          docker push $IMAGE:latest

      - name: Set kubectl context
        run: gcloud container clusters get-credentials gke-cluster --zone us-central1-a --project my-gke-project11

      - name: Configure kubectl for GKE
        run: |
          gcloud container clusters get-credentials gke-cluster --zone us-central1-a --project my-gke-project11
          # 👇 Install the GKE auth plugin
          gcloud components install gke-gcloud-auth-plugin --quiet
          export USE_GKE_GCLOUD_AUTH_PLUGIN=True

      - name: Deploy to GKE
        run: |
          kubectl set image deployment/nginx-deployment nginx=$IMAGE:$GITHUB_SHA || kubectl apply -f k8s/
          kubectl rollout status deployment/nginx-deployment
